const test=require('node:test'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const S=require('../public/sync.js'),J=require('../public/core.js');
Object.defineProperty(globalThis,'crypto',{value:webcrypto,configurable:true});
Object.defineProperty(globalThis,'navigator',{value:{locks:{request:async(_name,_options,fn)=>fn({})}},configurable:true});
const secret=S.encode(crypto.getRandomValues(new Uint8Array(32))),code=S.pairing('https://jeebtak-test.workers.dev',secret);
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
function server(){let value={revision:0,box:null},offline=false,requests=[];return {requests,get value(){return value;},set offline(v){offline=v;},fetch:async(url,opts)=>{requests.push({url,...opts});if(offline)throw Error('offline');if(opts.method==='PUT'){const body=JSON.parse(opts.body);if(body.revision!==value.revision)return Response.json({}, {status:409});value={revision:value.revision+1,box:body.box};return Response.json({revision:value.revision});}return Response.json(value);}};}
function device(net,initial=J.empty()){const storage=memory();storage.setItem(S.KEY,JSON.stringify(initial));let active=true,applied=0;const engine=new S.Engine({storage,fetch:net.fetch,validate:s=>J.validate(s||J.empty()),active:()=>active,onApply:()=>applied++});return {engine,storage,get applied(){return applied;},set active(v){active=v;},data:()=>JSON.parse(storage.getItem(S.KEY)),edit:fn=>{const x=JSON.parse(storage.getItem(S.KEY));fn(x);storage.setItem(S.KEY,JSON.stringify(x));}};}
test('AES-GCM ciphertext hides financial names and fails on tamper or wrong key',async()=>{const key=await S.keys(secret),box=await S.encrypt({name:'private salary',amount:1234},key.aes);assert.doesNotMatch(JSON.stringify(box),/private salary|1234/);assert.deepEqual(await S.decrypt(box,key.aes),{name:'private salary',amount:1234});const other=await S.keys(S.encode(crypto.getRandomValues(new Uint8Array(32))));await assert.rejects(()=>S.decrypt(box,other.aes));await assert.rejects(()=>S.decrypt({...box,data:(box.data[0]==='a'?'b':'a')+box.data.slice(1)},key.aes));assert.notEqual((await S.encrypt({x:1},key.aes)).iv,(await S.encrypt({x:1},key.aes)).iv);});
test('pairing code accepts HTTPS worker only and is not a URL carrying a secret',()=>{assert.deepEqual(S.parsePairing(code),{endpoint:'https://jeebtak-test.workers.dev',key:secret});for(const url of ['http://jeebtak-test.workers.dev','https://evil.example','https://a.workers.dev/?key=secret','https://user:pass@a.workers.dev'])assert.throws(()=>S.parsePairing(S.pairing(url,secret)));});
test('unpaired wallets never make network requests',async()=>{const net=server(),a=device(net);await a.engine.tick();assert.equal(net.requests.length,0);});
test('disconnect in another tab during a request cannot resurrect pairing',async()=>{const net=server(),a=device(net);await a.engine.pair(code);a.edit(s=>s.salary.amount=20);const original=a.engine.fetch;a.engine.fetch=async(...args)=>{const result=await original(...args);a.storage.removeItem(S.CONFIG);return result;};await a.engine.tick();assert.equal(a.engine.connected(),false);assert.equal(a.data().salary.amount,20);});
test('two devices converge; each keeps its own PIN and appearance',async()=>{const net=server(),a=device(net),b=device(net);a.edit(s=>{s.salary.amount=900;s.settings.pin={salt:'a'.repeat(32),hash:'b'.repeat(64)};s.settings.theme='dark';});await a.engine.pair(code);await b.engine.pair(code);assert.equal(b.engine.status,'conflict');await b.engine.tick('remote');assert.equal(b.data().salary.amount,900);b.edit(s=>s.salary.amount=1100);await b.engine.tick();await a.engine.tick();assert.equal(a.data().salary.amount,1100);assert.equal(a.data().settings.pin.hash,'b'.repeat(64));assert.equal(a.data().settings.theme,'dark');assert.equal(b.data().settings.pin,null);assert.equal(b.data().settings.theme,'system');const plain=await S.decrypt(net.value.box,(await S.keys(secret)).aes);assert.equal(plain.settings.pin,undefined);assert.equal(plain.settings.theme,undefined);assert.ok(net.requests.every(r=>!r.url.includes(secret)&&!r.body?.includes(secret)));});
test('offline changes survive reload and are uploaded on reconnection',async()=>{const net=server(),a=device(net);await a.engine.pair(code);net.offline=true;a.edit(s=>s.salary.amount=333);await a.engine.tick();assert.equal(a.data().salary.amount,333);const restored=new S.Engine({storage:a.storage,fetch:net.fetch,validate:J.validate,active:()=>true});net.offline=false;await restored.tick();assert.equal((await S.decrypt(net.value.box,(await S.keys(secret)).aes)).salary.amount,333);});
test('concurrent offline edits pause instead of overwriting; recovery keeps both versions',async()=>{const net=server(),a=device(net),b=device(net);await a.engine.pair(code);await b.engine.pair(code);a.edit(s=>s.salary.amount=100);b.edit(s=>s.salary.amount=200);await a.engine.tick();await b.engine.tick();assert.equal(b.engine.status,'conflict');assert.equal(b.data().salary.amount,200);assert.equal((await S.decrypt(net.value.box,(await S.keys(secret)).aes)).salary.amount,100);await b.engine.tick('local');await a.engine.tick();assert.equal(a.data().salary.amount,200);const backup=JSON.parse(b.storage.getItem(S.RECOVERY));assert.equal(backup.local.salary.amount,200);assert.equal(backup.remote.salary.amount,100);});
test('stale conflict approval cannot overwrite a newer remote update',async()=>{const net=server(),a=device(net),b=device(net);await a.engine.pair(code);await b.engine.pair(code);a.edit(s=>s.salary.amount=10);b.edit(s=>s.salary.amount=20);await a.engine.tick();await b.engine.tick();a.edit(s=>s.salary.amount=30);await a.engine.tick();await b.engine.tick('local');assert.equal(b.engine.status,'error');assert.equal((await S.decrypt(net.value.box,(await S.keys(secret)).aes)).salary.amount,30);});
test('locked, hidden or editing device never applies remote data',async()=>{const net=server(),a=device(net);await a.engine.pair(code);const count=net.requests.length;a.active=false;a.edit(s=>s.salary.amount=8);await a.engine.tick();assert.equal(net.requests.length,count);});
test('local data changed during a fetch is never overwritten',async()=>{const net=server(),a=device(net),b=device(net);await a.engine.pair(code);await b.engine.pair(code);a.edit(s=>s.salary.amount=10);await a.engine.tick();const original=b.engine.fetch;b.engine.fetch=async(...args)=>{const result=await original(...args);b.edit(s=>s.salary.amount=20);return result;};await b.engine.tick();assert.equal(b.data().salary.amount,20);assert.equal(b.applied,0);});
test('failed state write does not advance base and recover journal restores safely',async()=>{const net=server(),a=device(net),b=device(net);await a.engine.pair(code);await b.engine.pair(code);a.edit(s=>s.salary.amount=22);await a.engine.tick();const setter=b.storage.setItem;b.storage.setItem=(key,value)=>{if(key===S.KEY)throw Error('quota');setter(key,value);};await b.engine.tick();assert.equal(b.data().salary.amount,0);assert.equal(b.engine.status,'error');b.storage.setItem=setter;await b.engine.tick();assert.equal(b.data().salary.amount,22);assert.equal(b.engine.config().journal,undefined);});
test('disconnect preserves finances and stops requests',async()=>{const net=server(),a=device(net);await a.engine.pair(code);const before=a.storage.getItem(S.KEY);a.engine.disconnect();const count=net.requests.length;await a.engine.tick();assert.equal(net.requests.length,count);assert.equal(a.storage.getItem(S.KEY),before);});
test('wrong credentials leave device unpaired and finances untouched',async()=>{const net={fetch:async()=>new Response(null,{status:401})},a=device(net),before=a.storage.getItem(S.KEY);await assert.rejects(()=>a.engine.pair(code));assert.equal(a.engine.connected(),false);assert.equal(a.storage.getItem(S.KEY),before);});
