const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../public/sw.js'),'utf8');
function boot(fail=false){const events={},calls=[],store=new Map([['jeebtak-app-v4',new Map()],['jeebtak-app-v5',new Map()],['another-app',new Map()]]);let active='v4',read;
 const caches={open:async name=>({addAll:async requests=>{calls.push('download');assert.ok(requests.every(r=>r.cache==='reload'));if(fail)throw Error('offline');store.set(name,new Map([['https://example.test/index.html','NEW HTML']]));}}),keys:async()=>[...store.keys()],delete:async name=>{calls.push('delete:'+name);store.delete(name);},match:async(url,opts)=>{read=opts.cacheName;return store.get(opts.cacheName)?.get(url);}};
 vm.runInNewContext(source,{URL,Request,caches,fetch:async()=>{throw Error('offline');},self:{location:{origin:'https://example.test',href:'https://example.test/sw.js'},addEventListener:(name,fn)=>events[name]=fn,skipWaiting:async()=>{calls.push('skipWaiting');active='v6';},clients:{claim:async()=>calls.push('claim'),matchAll:async()=>{throw Error('Must not navigate existing windows');}}}});
 const run=name=>{let p;events[name]({waitUntil:x=>p=x});return p;};return {run,calls,store,get active(){return active;},get read(){return read;},navigate:()=>{let p;events.fetch({request:{method:'GET',url:'https://example.test/',mode:'navigate'},respondWith:x=>p=x});return p;}};
}
test('v4/v5 upgrade becomes active after complete download even with old windows present',async()=>{const app=boot();await app.run('install');assert.deepEqual(app.calls,['download','skipWaiting']);assert.equal(app.active,'v6');await app.run('activate');assert.equal(await app.navigate(),'NEW HTML');assert.equal(app.read,'jeebtak-app-v6');assert.ok(app.store.has('another-app'));assert.ok(!app.store.has('jeebtak-app-v4'));assert.ok(!app.store.has('jeebtak-app-v5'));assert.ok(app.calls.includes('claim'));});
test('failed upgrade leaves old cache available and never skips waiting',async()=>{const app=boot(true);await assert.rejects(app.run('install'));assert.equal(app.active,'v4');assert.ok(app.store.has('jeebtak-app-v4'));assert.deepEqual(app.calls,['download']);});
